# coding: utf-8

"""
    FurFinds

    Find. Adopt. Love.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.pets_api import PetsApi


class TestPetsApi(unittest.TestCase):
    """PetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PetsApi()

    def tearDown(self) -> None:
        pass

    def test_add_pet_pets_post(self) -> None:
        """Test case for add_pet_pets_post

        Add Pet
        """
        pass

    def test_adopt_pet_pets_id_adopt_post(self) -> None:
        """Test case for adopt_pet_pets_id_adopt_post

        Adopt Pet
        """
        pass

    def test_list_pets_pets_get(self) -> None:
        """Test case for list_pets_pets_get

        List Pets
        """
        pass


if __name__ == '__main__':
    unittest.main()
