# coding: utf-8

"""
    FurFinds

    Find. Adopt. Love.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pet_response import PetResponse

class TestPetResponse(unittest.TestCase):
    """PetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PetResponse:
        """Test PetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PetResponse`
        """
        model = PetResponse()
        if include_optional:
            return PetResponse(
                id = 56,
                name = '',
                type = '',
                adopted = True
            )
        else:
            return PetResponse(
                id = 56,
                name = '',
                type = '',
                adopted = True,
        )
        """

    def testPetResponse(self):
        """Test PetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
