# coding: utf-8

"""
    FurFinds

    Find. Adopt. Love.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pet_create import PetCreate

class TestPetCreate(unittest.TestCase):
    """PetCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PetCreate:
        """Test PetCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PetCreate`
        """
        model = PetCreate()
        if include_optional:
            return PetCreate(
                name = '',
                type = ''
            )
        else:
            return PetCreate(
                name = '',
                type = '',
        )
        """

    def testPetCreate(self):
        """Test PetCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
