"""create pets table

Revision ID: bfdfd83722e5
Revises: 
Create Date: 2026-04-20 12:42:40.461527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfdfd83722e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("adopted", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pets_id"), "pets", ["id"], unique=False)
    op.create_index(op.f("ix_pets_name"), "pets", ["name"], unique=False)
    op.create_index(op.f("ix_pets_type"), "pets", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pets_type"), table_name="pets")
    op.drop_index(op.f("ix_pets_name"), table_name="pets")
    op.drop_index(op.f("ix_pets_id"), table_name="pets")
    op.drop_table("pets")
    # ### end Alembic commands ###
